# Generated by Django 4.2.4 on 2023-08-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseKPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('file', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegularKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kpi_type', models.CharField(editable=False, max_length=50)),
                ('current_number', models.IntegerField()),
                ('total_number', models.IntegerField()),
                ('percentage', models.CharField(max_length=4)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dashboard')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.basekpitemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateTimeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kpi_type', models.CharField(editable=False, max_length=50)),
                ('days', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dashboard')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.basekpitemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChartKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kpi_type', models.CharField(editable=False, max_length=50)),
                ('data', models.JSONField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dashboard')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.basekpitemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
