# Generated by Django 4.2.4 on 2023-08-18 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseKPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('file', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BaseKPITemplateContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='kpi_card.html', max_length=50)),
                ('col_span_lg', models.IntegerField(default=1)),
                ('col_span_md', models.IntegerField(default=1)),
                ('col_span_sm', models.IntegerField(default=1)),
                ('row_span_lg', models.IntegerField(default=1)),
                ('row_span_md', models.IntegerField(default=1)),
                ('row_span_sm', models.IntegerField(default=1)),
                ('order_lg', models.IntegerField(default=1)),
                ('order_md', models.IntegerField(default=1)),
                ('order_sm', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dark_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='dashboard_section.html', max_length=50)),
                ('grid_cols_sm', models.IntegerField(default=1)),
                ('grid_cols_md', models.IntegerField(default=2)),
                ('grid_cols_lg', models.IntegerField(default=3)),
                ('mt', models.IntegerField(default=1)),
                ('mb', models.IntegerField(default=1)),
                ('ml', models.IntegerField(default=1)),
                ('mr', models.IntegerField(default=1)),
                ('gap', models.IntegerField(default=4)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='RegularKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('kpi_type', models.CharField(editable=False, max_length=50)),
                ('current_number', models.IntegerField()),
                ('total_number', models.IntegerField()),
                ('percentage', models.CharField(max_length=4)),
                ('dashboard_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dashboardsection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.basekpitemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateTimeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('kpi_type', models.CharField(editable=False, max_length=50)),
                ('days', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('dashboard_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dashboardsection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.basekpitemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChartKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('kpi_type', models.CharField(editable=False, max_length=50)),
                ('data', models.JSONField()),
                ('dashboard_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dashboardsection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.basekpitemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basekpitemplate',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.basekpitemplatecontainer'),
        ),
    ]
